version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - m98trading_postgres_data:/var/lib/postgresql/data
    networks:
      - m98trading-nw
  web:
    build: .
    command: bash -c "make dev-setup && make server"
    volumes:
      - ./:/app
      - ./certs:/etc/ssl/certs
    ports:
      - "8000:8000"
    env_file:
      - ./m98trading/settings/.env
    networks:
      - m98trading-nw
    depends_on:
      - db
      - redis
  celery:
    restart: always
    build: .
    command: bash -c "make celery"
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    networks:
      - m98trading-nw
  celery_bot:
    restart: always
    build: .
    command: bash -c "make celery_bot"
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    networks:
      - m98trading-nw
  celery_beat:
    restart: always
    build: .
    command: bash -c "make celery_beat"
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    networks:
      - m98trading-nw
  redis:
    restart: always
    image: redis:6.2-alpine
    networks:
      - m98trading-nw
    ports:
      - "6371:6379"
  rabbitmq:
    image: 'bitnami/rabbitmq:3.12.7'
    networks:
      - m98trading-nw
    environment:
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
volumes:
  m98trading_postgres_data:
    driver: local

networks:
  m98trading-nw:
    driver: bridge
